In [1]:
pip install tensorflow


Import tensorflow library

In [2]:
import tensorflow as tf

create tensors

In [5]:
# Create a scalar (0-D tensor)#
a=tf.constant(10)
print(a)
# Create a vector (1-D tensor)
v=tf.constant([1,2,34,3])
print(v)
# Create a matrix (2-D tensor)
m=tf.constant([[1,2],[3,4]])
print(m)
# Create a 3-D tensor
t3=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(t3)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([ 1  2 34  3], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [13]:
# Addition of tensors
a=tf.constant([10,20,30])
b=tf.constant([1,23,34])
c=tf.add(a,b)
print(c)
# Subtraction of tensors
c=tf.subtract(a,b)
print(c)
# Element-wise multiplication
c=tf.multiply(a,b)
print(c)
# Division of tensors
c=tf.divide(a,b)
print(c)

tf.Tensor([11 43 64], shape=(3,), dtype=int32)
tf.Tensor([ 9 -3 -4], shape=(3,), dtype=int32)
tf.Tensor([  10  460 1020], shape=(3,), dtype=int32)
tf.Tensor([10.          0.86956522  0.88235294], shape=(3,), dtype=float64)


datatype and shape of sensor

In [15]:
import numpy as np
a = np.array([1,2,3,4,5])
b = tf.convert_to_tensor(a)
b

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

NUMPY ARRAY TO TENSOR

In [18]:
import numpy as np
np_array=np.array([[1,2,3],[3,56,34]])
tensor=tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[ 1  2  3]
 [ 3 56 34]], shape=(2, 3), dtype=int64)
